spring.application.name=courseregistration
# Thông tin kết nối đến database course_registration_system
spring.datasource.url=jdbc:mysql://localhost:3306/course_registration_system?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Nickkyg2k6

# Cài đặt hiển thị câu lệnh SQL ra màn hình để dễ theo dõi
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect